### ISSUE TITLE
test_no_rewind_into_previous_inline fails with ruby 2.1

### ISSUE THREAD

**Issue by lnussbaum** [vmg/redcarpet#485]
Hi,

I get:
```
========================================================================================================================================
Error: test_no_rewind_into_previous_inline(MarkdownTest)
: NoMethodError: undefined method `render' for #<MarkdownTest:0x00000001dafc40>
/home/lucas/d/debian/pkg-ruby-extras/ruby-redcarpet/test/markdown_test.rb:314:in `test_no_rewind_into_previous_inline'
     311: 
     312:   def test_no_rewind_into_previous_inline
     313:     result = "<p><em>!dl</em><a href=\"mailto:1@danlec.com\">1@danlec.com</a></p>\n"
  => 314:     output = render("_!dl_1@danlec.com", with: [:autolink])
     315: 
     316:     assert_equal result, output
     317: 
======================================================================================================================
```

This patch fixes it:
```
--- a/test/markdown_test.rb
+++ b/test/markdown_test.rb
@@ -311,12 +311,12 @@ text
 
   def test_no_rewind_into_previous_inline
     result = "<p><em>!dl</em><a href=\"mailto:1@danlec.com\">1@danlec.com</a></p>\n"
-    output = render("_!dl_1@danlec.com", with: [:autolink])
+    output = render_with({:autolink => true}, "_!dl_1@danlec.com")
 
     assert_equal result, output
 
     result = "<p>abc123<em><a href=\"http://www.foo.com\">www.foo.com</a></em>@foo.com</p>\n"
-    output = render("abc123_www.foo.com_@foo.com", with: [:autolink])
+    output = render_with({:autolink => true}, "abc123_www.foo.com_@foo.com")
 
     assert_equal result, output
   end
```

**Comment by robin850** [comment]
Ah yes, my bad! Actually the `render` helper has been introduced in https://github.com/vmg/redcarpet/commit/85d4bdd58a069d91605aa0678f7e7e80fec3742f but it's not available on the `3-2-branch` branch. https://github.com/vmg/redcarpet/commit/aab019eec1e7b765319d827607b64e98df704462 has been pushed (crediting you) to address that but we are most-likely not going to release any new 3.2.x version ; anyway, thanks for reporting! :-)
