### ISSUE TITLE
RedCarpet 3.6.1 has an incorrect required_ruby_version

### ISSUE THREAD

**Issue by jeremyevans** [vmg/redcarpet#802]
It lists the required_ruby version as 1.9.2, but is does not compile on Ruby 2.0.0 (and presumably 1.9.2 or 1.9.3):

```
rc_markdown.c:96:9: error: ¿RUBY_TYPED_FREE_IMMEDIATELY¿ undeclared here (not in
a function)
   96 |         RUBY_TYPED_FREE_IMMEDIATELY | RUBY_TYPED_WB_PROTECTED,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
rc_markdown.c:96:39: error: ¿RUBY_TYPED_WB_PROTECTED¿ undeclared here (not in a
function)
   96 |         RUBY_TYPED_FREE_IMMEDIATELY | RUBY_TYPED_WB_PROTECTED,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~
rc_markdown.c:96:9: warning: excess elements in struct initializer
   96 |         RUBY_TYPED_FREE_IMMEDIATELY | RUBY_TYPED_WB_PROTECTED,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
rc_markdown.c:96:9: note: (near initialization for ¿rb_redcarpet_md__type¿)
make: *** [Makefile:224: rc_markdown.o] Error 1
```

Probably not worth keeping support for Ruby 2.0, so I recommend you bump required_ruby_version to 2.1.
